include(FetchContent)

function(fetch_make_available_stb library_name)
	FetchContent_Declare_URL_Populate(${library_name} https://github.com/nothings/stb/archive/refs/heads/master.zip)

    # Copy needed files to proper location
    set(STB_INC_DIR "${${library_name}_SOURCE_DIR}/fox_stb/stb")

    set(STB_SOURCE_DIR "${${library_name}_SOURCE_DIR}")

    file(MAKE_DIRECTORY ${STB_INC_DIR})

    file(
        COPY 
        "${STB_SOURCE_DIR}/stb_dxt.h"
        "${STB_SOURCE_DIR}/stb_image.h"
        "${STB_SOURCE_DIR}/stb_image_resize.h"
        "${STB_SOURCE_DIR}/stb_image_write.h"
        
        DESTINATION
        "${STB_INC_DIR}/"
        )

    # Generate config file
    
    file(WRITE "${STB_INC_DIR}/stb_impl.cpp" 
"// AUTOGENERATED WITH CMAKE
#pragma once

#include <cstring>

#define STB_DXT_IMPLEMENTATION
#include <stb/stb_dxt.h>

#define STB_IMAGE_IMPLEMENTATION
#include <stb/stb_image.h>

#define STB_IMAGE_RESIZE_IMPLEMENTATION
#include <stb/stb_image_resize.h>

#define STB_IMAGE_WRITE_IMPLEMENTATION
#include <stb/stb_image_write.h>

")

    
    add_library(
        ${library_name} 
        STATIC
        "${STB_INC_DIR}/stb_impl.cpp"
		
		"${STB_INC_DIR}/stb_dxt.h"
        "${STB_INC_DIR}/stb_image.h"
        "${STB_INC_DIR}/stb_image_resize.h"
        "${STB_INC_DIR}/stb_image_write.h"
    )

    target_include_directories(${library_name} PUBLIC "${STB_INC_DIR}/../")

    add_library(fox.cmake::${library_name} ALIAS ${library_name})

endfunction()